# Please make changes directly to the 'template' file:

#     .pre-commit-template.yaml

# and run the script './pc.sh' from this directory to update this file.

# Please do not make changes directly to the 'config' file. The 'config' file:

#     .pre-commit-config.yaml

# is created and updated by the pc.sh script found in the same directory
# in order to maintain the correct, current master sha 
# # copyright (c) 2019 Michael Treanor (https://www.github.com/skeptycal)
# # MIT License <https://opensource.org/licenses/MIT>


default_language_version:
    python: python3.7
exclude: '^$'
fail_fast: false
repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-docstring-first
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: detect-private-key
    -   id: flake8
    -   id: requirements-txt-fixer
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: master
    hooks:
    -   id: pylint
